name: quran
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  dartz:
  get_it: ^7.2.0
  bloc:
  flutter_bloc: ^8.1.2
  google_fonts_arabic: ^1.1.7
  persian_fonts: ^1.0.5
  audioplayers: ^3.0.1
  hex: ^0.2.0
  glass: ^1.0.1+1
  glassmorphism: ^3.0.0
  page_transition: ^2.0.9
  just_audio: ^0.9.31
  shared_preferences: ^2.0.20
  flutter_staggered_animations: ^1.1.1
  dotted_border: ^2.0.0+3
  geolocator: 
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  al_quran: ^0.1.1+5
  flutter_qiblah: ^2.1.0
  share_plus: ^4.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  google_speech: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
    - family: AR
      fonts:
        - asset: fonts/ReemKufi-VariableFont_wght.ttf
    - family: kit
      fonts:
        - asset: fonts\alfont_com_SakkalKitab-Regular.ttf
   
